<?php

return [

    /*
    |--------------------------------------------------------------------------
    | STATIC STRINGS TRANSLATIONS
    |--------------------------------------------------------------------------
    |
    |  !!! WARNING - This is a file generated by the LanguagesService. !!!
    |  You should not modify it, as it shall be replaced next time this service is executed.
    |
     */

    'success_message' => 'Ваш ответ успешно отправлен.',
    'error_message' => 'Операция не удалась, повторите попытку позже.',

];
