<?php

return [

    /*
    |--------------------------------------------------------------------------
    | STATIC STRINGS TRANSLATIONS
    |--------------------------------------------------------------------------
    |
    |  !!! WARNING - This is a file generated by the LanguagesService. !!!
    |  You should not modify it, as it shall be replaced next time this service is executed.
    |
     */

    'success_message' => 'Your reply has been sent successfully.',
    'error_message' => 'The operation failed, try again later.',

];
