<?php

return [

    /*
    |--------------------------------------------------------------------------
    | STATIC STRINGS TRANSLATIONS
    |--------------------------------------------------------------------------
    |
    |  !!! WARNING - This is a file generated by the LanguagesService. !!!
    |  You should not modify it, as it shall be replaced next time this service is executed.
    |
     */

    'success_message' => 'Ձեր պատասխանը հաջողությամբ ուղարկված է։',
    'error_message' => 'Գործողությունը ձախողվեց, փորձեք մի փոքր ուշ։',

];
