<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
  */

  'reset' => 'Ձեր գաղտնաբառը վերականգնվել է:',
  'hrottled' => 'Խնդրում ենք սպասել նախքան նորից փորձելը:',
  'sent' => 'Ձեր էլ․ փոստին ուղարկվել է գաղտնաբառը վերականգնելու հղումը:',
  'token' => 'Գաղտնաբառի վերականգնման այս նշանն անվավեր է:',
  'user' => 'Մենք չենք կարող գտնել այդ էլփոստի հասցեով օգտվող:',

];
